// Code generated by github.com/frm-adiputra/csv2postgres DO NOT EDIT

package target003

// Computer implements pipeline.Computer interface.
type Computer struct {
}

// Compute compute field's values.
func (c Computer) Compute(fields map[string]interface{}) (map[string]interface{}, error) {
	return fields, nil
}
