// Code generated by github.com/frm-adiputra/csv2postgres DO NOT EDIT

package target003

import (
	"github.com/frm-adiputra/csv2postgres/utils"
)

// Converter implements pipeline.Converter interface.
type Converter struct{}

// Convert converts field's values.
func (c Converter) Convert(fields map[string]interface{}) (map[string]interface{}, error) {
	if fields["calon"] == "" {
		return nil, utils.ErrEmptyValue("calon")
	}
	vCalon := fields["calon"]
	fields["calon"] = vCalon

	return fields, nil
}
