// Code generated by github.com/frm-adiputra/csv2postgres DO NOT EDIT

package target003

// Validator implements pipeline.Validator interface.
type Validator struct{}

// Validate validates field's values.
func (c Validator) Validate(fields map[string]interface{}) error {
	return nil
}
