// Code generated by github.com/frm-adiputra/csv2postgres DO NOT EDIT

package target001

// Computer implements pipeline.Computer interface.
type Computer struct {
	NimToEmailSaltedHash func(string) (string, error)
}

// Compute compute field's values.
func (c Computer) Compute(fields map[string]interface{}) (map[string]interface{}, error) {
	vNim_email_hashed, err := c.NimToEmailSaltedHash(fields["nim_email_hashed"].(string))
	if err != nil {
		return nil, err
	}
	fields["nim_email_hashed"] = vNim_email_hashed
	return fields, nil
}
