// Code generated by github.com/frm-adiputra/csv2postgres DO NOT EDIT

package target001

import (
	"github.com/frm-adiputra/csv2postgres/utils"
)

// Converter implements pipeline.Converter interface.
type Converter struct{}

// Convert converts field's values.
func (c Converter) Convert(fields map[string]interface{}) (map[string]interface{}, error) {
	if fields["nim_email_hashed"] == "" {
		return nil, utils.ErrEmptyValue("nim_email_hashed")
	}
	vNim_email_hashed := fields["nim_email_hashed"]
	fields["nim_email_hashed"] = vNim_email_hashed
	if fields["dapil"] == "" {
		return nil, utils.ErrEmptyValue("dapil")
	}
	vDapil := fields["dapil"]
	fields["dapil"] = vDapil

	return fields, nil
}
