// Code generated by github.com/frm-adiputra/csv2postgres DO NOT EDIT

package target002

// Computer implements pipeline.Computer interface.
type Computer struct {
	SaltedHash func(string) (string, error)
	JenisEmail func(string) (string, error)
}

// Compute compute field's values.
func (c Computer) Compute(fields map[string]interface{}) (map[string]interface{}, error) {
	vNim_email_hashed, err := c.SaltedHash(fields["nim_email_hashed"].(string))
	if err != nil {
		return nil, err
	}
	fields["nim_email_hashed"] = vNim_email_hashed
	vJenis_email, err := c.JenisEmail(fields["jenis_email"].(string))
	if err != nil {
		return nil, err
	}
	fields["jenis_email"] = vJenis_email
	return fields, nil
}
