// Code generated by github.com/frm-adiputra/csv2postgres DO NOT EDIT

package target002

import (
	"github.com/frm-adiputra/csv2postgres/utils"
)

// Converter implements pipeline.Converter interface.
type Converter struct{}

// Convert converts field's values.
func (c Converter) Convert(fields map[string]interface{}) (map[string]interface{}, error) {
	if fields["waktu_str"] == "" {
		return nil, utils.ErrEmptyValue("waktu_str")
	}
	vWaktu_str := fields["waktu_str"]
	fields["waktu_str"] = vWaktu_str
	if fields["nim_email_hashed"] == "" {
		return nil, utils.ErrEmptyValue("nim_email_hashed")
	}
	vNim_email_hashed := fields["nim_email_hashed"]
	fields["nim_email_hashed"] = vNim_email_hashed
	if fields["jenis_email"] == "" {
		return nil, utils.ErrEmptyValue("jenis_email")
	}
	vJenis_email := fields["jenis_email"]
	fields["jenis_email"] = vJenis_email
	if fields["persetujuan"] == "" {
		return nil, utils.ErrEmptyValue("persetujuan")
	}
	vPersetujuan := fields["persetujuan"]
	fields["persetujuan"] = vPersetujuan
	if fields["dapil"] == "" {
		return nil, utils.ErrEmptyValue("dapil")
	}
	vDapil := fields["dapil"]
	fields["dapil"] = vDapil
	if fields["pilihan_gubernur"] == "" {
		return nil, utils.ErrEmptyValue("pilihan_gubernur")
	}
	vPilihan_gubernur := fields["pilihan_gubernur"]
	fields["pilihan_gubernur"] = vPilihan_gubernur
	if fields["pilihan_dpm"] == "" {
		return nil, utils.ErrEmptyValue("pilihan_dpm")
	}
	vPilihan_dpm := fields["pilihan_dpm"]
	fields["pilihan_dpm"] = vPilihan_dpm
	vPilihan_himatro, err := utils.StringToNullString(fields["pilihan_himatro"].(string))
	if err != nil {
		return nil, utils.FieldError{Field: "pilihan_himatro", Message: err.Error()}
	}
	fields["pilihan_himatro"] = vPilihan_himatro
	vPilihan_hmti, err := utils.StringToNullString(fields["pilihan_hmti"].(string))
	if err != nil {
		return nil, utils.FieldError{Field: "pilihan_hmti", Message: err.Error()}
	}
	fields["pilihan_hmti"] = vPilihan_hmti

	return fields, nil
}
