// Code generated by github.com/frm-adiputra/csv2postgres DO NOT EDIT

package target002

import "github.com/frm-adiputra/csv2postgres/pipeline"

// NewCSVReader creates a new CSVReader.
func NewCSVReader() *pipeline.CSVReader {
	return &pipeline.CSVReader{
		FileName:  "data/PEMILIHAN UMUM MAHASISWA ELECTRONIC VOTE FAKULTAS TEKNIK UNIVERSITAS TRUNOJOYO MADURA .csv",
		Separator: ',',
	}
}
